
--TABLA PACIENTE
CREATE TABLE PACIENTE(
ID_PACIENTE CHAR(5) CONSTRAINT PACIENTE_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT PA_NOM_NN NOT NULL,
APATERNO VARCHAR2(50) CONSTRAINT PA_AP_NN NOT NULL,
AMATERNO VARCHAR2(50),
EDAD VARCHAR2(10),
PESO VARCHAR2(10),
ESTATURA VARCHAR2(10),
TELEFONO VARCHAR2(10)
);
INSERT INTO PACIENTE VALUES('P1','DANIEL','MORALES','CASTILLO','27','78','1.7','4922190147');
INSERT INTO PACIENTE VALUES('P2','ROBERTO','MARTINEZ','REYES','33','72','1.8','4922223456');
INSERT INTO PACIENTE VALUES('P3','ALBERTO','MENDOZA','DOMINGUEZ','28','80','1.85','4927775676');
INSERT INTO PACIENTE VALUES('P4','JUAN','PEREZ','PEREZ','17','66','1.65','4928908762');
INSERT INTO PACIENTE VALUES('P5','PAULINA','ALVARADO','CASTILLO','15','54','1.67','4926667879');
SELECT * FROM PACIENTE;


--TABLA ASISTENTE
CREATE TABLE ASISTENTE(
ID_ASISTENTE CHAR(5) CONSTRAINT ASISTENTE_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT ASIS_NOM_NN NOT NULL,
APATERNO VARCHAR2(50) CONSTRAINT ASIS_AP_NN NOT NULL,
AMATERNO VARCHAR2(50),
TELEFONO VARCHAR2(10),
);
INSERT INTO ASISTENTE VALUES('A1','ALFONSO','PEREZ','ROBLES','4921334576');
INSERT INTO ASISTENTE VALUES('A2','JUAN','MARTINEZ','MARTINEZ','4921334577');
INSERT INTO ASISTENTE VALUES('A3','LUIS','MENDEZ','SANCHEZ','4921334578');
INSERT INTO ASISTENTE VALUES('A4','ALDONSO','BECERRA','SANCHEZ','4921334579');
INSERT INTO ASISTENTE VALUES('A5','GUSTAVO','CEPEDA','VALLES','4921334580');
SELECT * FROM ASISTENTE;



--TABLA MEDICO
CREATE TABLE MEDICO(
ID_MEDICO CHAR(5) CONSTRAINT MEDICO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT MED_NOM_NN NOT NULL,
APATERNO VARCHAR2(50) CONSTRAINT MED_AP_NN NOT NULL,
AMATERNO VARCHAR2(50),
TELEFONO VARCHAR2(10),
);
INSERT INTO MEDICO VALUES('M1','ADOLFO ','ROBLES','MENDEZ','4921217597');
INSERT INTO MEDICO VALUES('M2','ANDREA','ROBLES','SALAS','4921217598');
INSERT INTO MEDICO VALUES('M3','LUIS','JACINTO','LLAMAS','4921217599');
INSERT INTO MEDICO VALUES('M4','ISMAEL','MORALES','ROSALES','4921217799');
INSERT INTO MEDICO VALUES('M5','ANGELICA','CASTILLO','GONZALEZ','4921217789');

SELECT * FROM MEDICO;


--TABLA CONSULTORIO
CREATE TABLE CONSULTORIO(
ID_CONSULTORIO CHAR(5) CONSTRAINT CONSULTORIO_PK PRIMARY KEY,
HORARIO CHAR(5)
);
INSERT INTO CONSULTORIO VALUES('C1','7AM');
INSERT INTO CONSULTORIO VALUES('C2','8PM');
INSERT INTO CONSULTORIO VALUES('C3','9PM');
INSERT INTO CONSULTORIO VALUES('C4','10AM');
INSERT INTO CONSULTORIO VALUES('C5','11AM');
SELECT * FROM CONSULTORIO;


--TABLA TIPO ANALISIS
CREATE TABLE TIPO_ANALISIS(
ID_TIPO_ANALISIS CHAR(5) CONSTRAINT TIPO_ANALISIS_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT TA_NOM_NN NOT NULL
);
INSERT INTO TIPO_ANALISIS VALUES ('TA1','SANGRE');
INSERT INTO TIPO_ANALISIS VALUES ('TA2','LEUCOCITOS');
INSERT INTO TIPO_ANALISIS VALUES ('TA3','AZUCAR');
INSERT INTO TIPO_ANALISIS VALUES ('TA4','ORINA');
INSERT INTO TIPO_ANALISIS VALUES ('TA5','CARDIOLOGICO');
SELECT * FROM TIPO_ANALISIS;


--TABLA MEDICAMENTO
CREATE TABLE MEDICAMENTO(
ID_MEDICAMENTO CHAR(5) CONSTRAINT MEDICAMENTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT MEDICA_NOM_NN NOT NULL,
CANTIDAD CHAR(5),
);
INSERT INTO MEDICAMENTO VALUES ('M1','PARACETAMOL','25GR');
INSERT INTO MEDICAMENTO VALUES ('M2','CLONAZEPAM','25GR');
INSERT INTO MEDICAMENTO VALUES ('M3','ASPIRINA','30GR');
INSERT INTO MEDICAMENTO VALUES ('M4','OMEOPRAZOL','25GR');
INSERT INTO MEDICAMENTO VALUES ('M5','GENOPRAZOL','50GR');
SELECT * FROM MEDICAMENTO;


--TABLA CUARTO
CREATE TABLE CUARTO(
NUM_CUARTO CHAR(5) CONSTRAINT CUARTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT CU_NOM_NN NOT NULL
);
INSERT INTO CUARTO VALUES ('C1','CUARTO 1');
INSERT INTO CUARTO VALUES ('C2','CUARTO 2');
INSERT INTO CUARTO VALUES ('C3','CUARTO 3');
INSERT INTO CUARTO VALUES ('C4','CUARTO 4');
INSERT INTO CUARTO VALUES ('C5','CUARTO 5');
SELECT * FROM CUARTO;


--TABLA ENFERMERA
CREATE TABLE ENFERMERA(
ID_ENFERMERA CHAR(5) CONSTRAINT ENFERMERA_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) CONSTRAINT ENF_NOM_NN NOT NULL,
APATERNO VARCHAR2(50) CONSTRAINT ENF_AP_NN NOT NULL,
AMATERNO VARCHAR2(50),
TELEFONO VARCHAR2(10),
);
INSERT INTO ENFERMERA VALUES('E1','CRISTINA','FERNANDEZ','SALAS','4921667538');
INSERT INTO ENFERMERA VALUES('E2','ALMA','ROBLES','ROBLES','4921667539');
INSERT INTO ENFERMERA VALUES('E3','DIANA','JIMENEZ','SANCHEZ','4921667540');
INSERT INTO ENFERMERA VALUES('E4','NATALIA','CASTRO','GOMEZ','4921667541');
INSERT INTO ENFERMERA VALUES('E5','ALEXA','ALVARADO','NUÑEZ','4921667542');
SELECT * FROM ENFERMERA;


--TABLA TIPO_CONSULTA

CREATE TABLE TIPO_CONSULTA(
ID_TIPO CHAR(5) CONSTRAINT TC_PK PRIMARY KEY,
TIPO VARCHAR2(25)
);

INSERT INTO TIPO_CONSULTA VALUES('E1','CRISTINA','FERNANDEZ','SALAS','4921667538');
INSERT INTO ENFERMERA VALUES('E2','ALMA','ROBLES','ROBLES','4921667539');
INSERT INTO ENFERMERA VALUES('E3','DIANA','JIMENEZ','SANCHEZ','4921667540');
INSERT INTO ENFERMERA VALUES('E4','NATALIA','CASTRO','GOMEZ','4921667541');
INSERT INTO ENFERMERA VALUES('E5','ALEXA','ALVARADO','NUÑEZ','4921667542');
SELECT * FROM ENFERMERA;




















CREATE TABLE CITA(
NUM_CITA CHAR(5) CONSTRAINT CI_NC_NN NOT NULL,
FECHA DATE CONSTRAINT CI_FE_NN NOT NULL,
ID_PACIENTE CHAR(5),
ID_ASISTENTE CHAR(5),
CONSTRAINT CITA_PK PRIMARY KEY (NUM_CITA,ID_PACIENTE,ID_ASISTENTE),
CONSTRAINT PAC_CI_FK FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
CONSTRAINT ASIS_CI_FK FOREIGN KEY (ID_ASISTENTE) REFERENCES ASISTENTE(ID_ASISTENTE)
);
INSERT INTO CITA VALUES ('CI001','20-05-2020','PA001','AS001');
INSERT INTO CITA VALUES ('CI002','20-05-2020','PA002','AS002');
INSERT INTO CITA VALUES ('CI003','20-05-2020','PA003','AS003');
INSERT INTO CITA VALUES ('CI004','20-05-2020','PA004','AS004');
INSERT INTO CITA VALUES ('CI005','20-05-2020','PA005','AS005');
INSERT INTO CITA VALUES ('CI006','20-05-2020','PA005','AS004');
INSERT INTO CITA VALUES ('CI007','20-05-2020','PA006','AS005');
INSERT INTO CITA VALUES ('CI008','20-05-2020','PA007','AS005');
SELECT * FROM CITA;

CREATE TABLE CONSULTA(
FOLIO_CONSULTA CHAR(5) CONSTRAINT CONSUL_FC_NN NOT NULL,
FECHA DATE CONSTRAINT CONSUL_FE_NN NOT NULL,
NUM_CITA CHAR(5),
ID_PACIENTE CHAR(5),
ID_ASISTENTE CHAR(5),
ID_MEDICO CHAR(5),
ID_CONSULTORIO CHAR(5),
CONSTRAINT CONSULTA_PK PRIMARY KEY (FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO),
CONSTRAINT CITA_CONSUL_FK FOREIGN KEY (NUM_CITA,ID_PACIENTE,ID_ASISTENTE) REFERENCES CITA(NUM_CITA,ID_PACIENTE,ID_ASISTENTE),
CONSTRAINT MED_CONSUL_FK FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
CONSTRAINT CONS_CONSUL_FK FOREIGN KEY (ID_CONSULTORIO) REFERENCES CONSULTORIO(ID_CONSULTORIO)
);
INSERT INTO CONSULTA VALUES ('FC001','29-05-2020','CI001','PA001','AS001','ME001','CO001');
INSERT INTO CONSULTA VALUES ('FC002','29-05-2020','CI002','PA002','AS002','ME002','CO002');
INSERT INTO CONSULTA VALUES ('FC003','29-05-2020','CI003','PA003','AS003','ME003','CO003');
INSERT INTO CONSULTA VALUES ('FC004','29-05-2020','CI004','PA004','AS004','ME004','CO004');
INSERT INTO CONSULTA VALUES ('FC005','29-05-2020','CI005','PA005','AS005','ME005','CO005');
INSERT INTO CONSULTA VALUES ('FC006','29-05-2020','CI006','PA005','AS004','ME005','CO005');
INSERT INTO CONSULTA VALUES ('FC007','29-05-2020','CI008','PA007','AS005','ME005','CO005');
SELECT * FROM CONSULTA;

CREATE TABLE ANALISIS_CLINICO(
NUM_ANALISIS CHAR(5) CONSTRAINT AC_NA_NN NOT NULL,
FOLIO_CONSULTA CHAR(5),
NUM_CITA CHAR(5),
ID_PACIENTE CHAR(5),
ID_ASISTENTE CHAR(5),
ID_MEDICO CHAR(5),
ID_CONSULTORIO CHAR(5),
ID_TIPO_ANALISIS CHAR(5),
CONSTRAINT ANALISIS_CLINICO_PK PRIMARY KEY (NUM_ANALISIS,FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO,ID_TIPO_ANALISIS),
CONSTRAINT CONS_AC_FK  FOREIGN KEY (FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO) REFERENCES CONSULTA(FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO),
CONSTRAINT TA_AC_FK FOREIGN KEY (ID_TIPO_ANALISIS) REFERENCES TIPO_ANALISIS(ID_TIPO_ANALISIS)
);
INSERT INTO ANALISIS_CLINICO VALUES ('AC001','FC001','CI001','PA001','AS001','ME001','CO001','TA001');
INSERT INTO ANALISIS_CLINICO VALUES ('AC002','FC002','CI002','PA002','AS002','ME002','CO002','TA002');
INSERT INTO ANALISIS_CLINICO VALUES ('AC003','FC003','CI003','PA003','AS003','ME003','CO003','TA003');
INSERT INTO ANALISIS_CLINICO VALUES ('AC004','FC004','CI004','PA004','AS004','ME004','CO004','TA004');
INSERT INTO ANALISIS_CLINICO VALUES ('AC005','FC005','CI005','PA005','AS005','ME005','CO005','TA005');
SELECT * FROM ANALISIS_CLINICO;

CREATE TABLE RECETA(
NUM_RECETA CHAR(5) CONSTRAINT REC_NC_NN NOT NULL,
FECHA DATE,
FOLIO_CONSULTA CHAR(5),
NUM_CITA CHAR(5),
ID_PACIENTE CHAR(5),
ID_ASISTENTE CHAR(5),
ID_MEDICO CHAR(5),
ID_CONSULTORIO CHAR(5),
ID_MEDICAMENTO CHAR(5),
CONSTRAINT RECETA_PK PRIMARY KEY (NUM_RECETA,FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO,ID_MEDICAMENTO),
CONSTRAINT CONS_RE_FK  FOREIGN KEY (FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO) REFERENCES CONSULTA(FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO),
CONSTRAINT MEDICA_RE_FK FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
INSERT INTO RECETA VALUES ('RE001','29-05-2020','FC001','CI001','PA001','AS001','ME001','CO001','ME001');
INSERT INTO RECETA VALUES ('RE002','29-05-2020','FC002','CI002','PA002','AS002','ME002','CO002','ME002');
INSERT INTO RECETA VALUES ('RE003','29-05-2020','FC003','CI003','PA003','AS003','ME003','CO003','ME003');
INSERT INTO RECETA VALUES ('RE004','29-05-2020','FC004','CI004','PA004','AS004','ME004','CO004','ME004');
INSERT INTO RECETA VALUES ('RE005','29-05-2020','FC005','CI005','PA005','AS005','ME005','CO005','ME005');
SELECT * FROM RECETA;

CREATE TABLE HOSPITALIZACION(
ID_HOSPITALIZACION CHAR(5) CONSTRAINT HOS_IH_NN NOT NULL,
FOLIO_CONSULTA CHAR(5),
NUM_CITA CHAR(5),
ID_PACIENTE CHAR(5),
ID_ASISTENTE CHAR(5),
ID_MEDICO CHAR(5),
ID_CONSULTORIO CHAR(5),
NUM_CUARTO CHAR(5),
ID_ENFERMERA CHAR(5),
CONSTRAINT HOSPITALIZACION_PK PRIMARY KEY (ID_HOSPITALIZACION,FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO,NUM_CUARTO,ID_ENFERMERA),
CONSTRAINT RE_HOS_FK  FOREIGN KEY (FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO) REFERENCES CONSULTA(FOLIO_CONSULTA,NUM_CITA,ID_PACIENTE,ID_ASISTENTE,ID_MEDICO,ID_CONSULTORIO),
CONSTRAINT CUA_HOS_FK FOREIGN KEY (NUM_CUARTO) REFERENCES CUARTO(NUM_CUARTO),
CONSTRAINT ENF_HOS_FK FOREIGN KEY (ID_ENFERMERA) REFERENCES ENFERMERA(ID_ENFERMERA)
);
INSERT INTO HOSPITALIZACION VALUES ('HO001','FC001','CI001','PA001','AS001','ME001','CO001','CU001','EN001');
INSERT INTO HOSPITALIZACION VALUES ('HO002','FC002','CI002','PA002','AS002','ME002','CO002','CU002','EN002');
INSERT INTO HOSPITALIZACION VALUES ('HO003','FC003','CI003','PA003','AS003','ME003','CO003','CU003','EN003');
INSERT INTO HOSPITALIZACION VALUES ('HO004','FC004','CI004','PA004','AS004','ME004','CO004','CU004','EN004');
INSERT INTO HOSPITALIZACION VALUES ('HO005','FC005','CI005','PA005','AS005','ME005','CO005','CU005','EN005');
INSERT INTO HOSPITALIZACION VALUES ('HO006','FC006','CI006','PA005','AS004','ME005','CO005','CU005','EN005');
SELECT * FROM HOSPITALIZACION;

--1: Consultar el nombre de completo de los m�dicos que han realizado al menos una consulta.
SELECT * FROM MEDICO;
SELECT * FROM CONSULTA;
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS TOTAL FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY APATERNO, AMATERNO, NOMBRE;
--2: Consultar el nombre completo de los pacientes que han sido consultados.
SELECT * FROM PACIENTE;
SELECT * FROM CONSULTA;
SELECT APATERNO || ' ' || AMATERNO || ' ' || NOMBRE AS PACIENTES_CONSULTADOS FROM PACIENTE P JOIN CONSULTA C 
ON P.ID_PACIENTE = C.ID_PACIENTE GROUP BY APATERNO, AMATERNO, NOMBRE;
--3: Consultar el nombre completo de los pacientes que han sido consultados e incluir el nombre completo del m�dico.
SELECT * FROM PACIENTE;
SELECT * FROM MEDICO;
SELECT * FROM CONSULTA;
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE AS PACIENTE_CONSULTADO,
       M.APATERNO || ' ' || M.AMATERNO || ' ' || M.NOMBRE AS MEDICO
       FROM PACIENTE P JOIN CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE
                       JOIN MEDICO M ON M.ID_MEDICO = C.ID_MEDICO;
--4: Consultar nombre completo de los pacientes y el tipo de an�lisis que se le han realizado.
SELECT * FROM ANALISIS_CLINICO;
SELECT * FROM TIPO_ANALISIS;
SELECT * FROM PACIENTE;
SELECT P.APATERNO, P.AMATERNO, P.NOMBRE,
       TA.NOMBRE AS ANALISIS FROM PACIENTE P JOIN ANALISIS_CLINICO AC ON P.ID_PACIENTE = AC.ID_PACIENTE
                                 JOIN TIPO_ANALISIS TA ON TA.ID_TIPO_ANALISIS = AC.ID_TIPO_ANALISIS;
--5: Consultar el nombre completo de los pacientes que han sido hospitalizados.
SELECT * FROM HOSPITALIZACION;
SELECT APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "PACIENTES HOSPITALIZADOS" FROM PACIENTE P JOIN HOSPITALIZACION H ON P.ID_PACIENTE = H.ID_PACIENTE;
--6: Consultar el nombre completo de los pacientes y el nombre de los medicamentos que le han sido recetados.
SELECT * FROM CONSULTA;
SELECT * FROM RECETA;
SELECT * FROM MEDICAMENTO;
SELECT P.APATERNO || ' ' || P.AMATERNO || ' ' || P.NOMBRE AS PACIENTE,
       M.NOMBRE AS MEDICAMENTO FROM PACIENTE P JOIN RECETA R ON P.ID_PACIENTE = R.ID_PACIENTE
                                               JOIN MEDICAMENTO M ON M.ID_MEDICAMENTO = R.ID_MEDICAMENTO;
--7: Consultar el nombre completo de los m�dicos y el total de consultas que han realizado.
SELECT * FROM MEDICO;
SELECT * FROM CONSULTA;
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS TOTAL FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY APATERNO, AMATERNO, NOMBRE;
--8: Consultar el nombre de los m�dicos que no han realizado consultas.
SELECT APATERNO || ' ' || AMATERNO || ' ' || NOMBRE AS MEDICOS_SIN_CONSULTAS FROM MEDICO WHERE ID_MEDICO NOT IN(SELECT ID_MEDICO FROM CONSULTA);
--9: Consultar el nombre completo de los pacientes y el total de consultas que ha tenido cada uno.
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS TOTAL_CONSULTAS FROM PACIENTE P JOIN CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE
GROUP BY APATERNO, AMATERNO, NOMBRE;
--10: Consultar el nombre de los medicamentos que no se han recetado.
SELECT * FROM RECETA;
SELECT * FROM MEDICAMENTO;
SELECT NOMBRE FROM MEDICAMENTO WHERE ID_MEDICAMENTO NOT IN(SELECT ID_MEDICAMENTO FROM RECETA);
-- 11: Consultar el nombre completo de los pacientes que m�s consultas han tenido
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS CONSULTAS FROM PACIENTE P JOIN CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) AS CONSULTAS FROM PACIENTE P JOIN CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE GROUP BY APATERNO, AMATERNO, NOMBRE);
-- 12: Consultar el nombre completo de los m�dicos que m�s consultas han tenido.
SELECT * FROM CONSULTA;
SELECT * FROM MEDICO;
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS CONSULTAS FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) AS CONSULTAS FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO GROUP BY APATERNO, AMATERNO, NOMBRE);
-- 13: Consultar el nombre completo de los pacientes que m�s han sido hospitalizados.
SELECT * FROM HOSPITALIZACION;
SELECT * FROM PACIENTE;
SELECT APATERNO, AMATERNO, NOMBRE, COUNT(*) AS HOSPITALIZACIONES FROM PACIENTE P JOIN HOSPITALIZACION H ON P.ID_PACIENTE = H.ID_PACIENTE
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) AS HOSPITALIZACIONES FROM PACIENTE P JOIN HOSPITALIZACION H ON P.ID_PACIENTE = H.ID_PACIENTE GROUP BY APATERNO, AMATERNO, NOMBRE);
-- 14: Consultar el nombre completo de las enfermeras que m�s pacientes han atendido.
SELECT * FROM HOSPITALIZACION;
SELECT * FROM ENFERMERA;
SELECT E.APATERNO, E.AMATERNO, E.NOMBRE, COUNT(*) AS PACIENTES FROM ENFERMERA E JOIN HOSPITALIZACION H ON E.ID_ENFERMERA = H.ID_ENFERMERA
                                                                          JOIN PACIENTE P ON P.ID_PACIENTE = H.ID_PACIENTE
GROUP BY E.APATERNO, E.AMATERNO, E.NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) AS PACIENTES FROM ENFERMERA E JOIN HOSPITALIZACION H ON E.ID_ENFERMERA = H.ID_ENFERMERA
                                                  JOIN PACIENTE P ON P.ID_PACIENTE = H.ID_PACIENTE
GROUP BY E.APATERNO, E.AMATERNO, E.NOMBRE);
-- 15: Consultar al m�dico del a�o (El m�dico que m�s consultas realiz� en un determinado a�o).
SELECT * FROM CONSULTA;
SELECT * FROM MEDICO;
SELECT ID_MEDICO FROM CONSULTA WHERE FECHA BETWEEN '01-01-20' AND '30-12-20';
SELECT M.APATERNO, M.AMATERNO, M.NOMBRE, COUNT(*) FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
                                                  JOIN PACIENTE P ON P.ID_PACIENTE = C.ID_PACIENTE
                                                   WHERE FECHA BETWEEN '01-01-20' AND '30-12-20'
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE);
-- 16: Consultar el nombre completo de los pacientes que no se han realizado an�lisis cl�nicos.
SELECT * FROM ANALISIS_CLINICO;
SELECT APATERNO || ' ' || AMATERNO || ' ' || NOMBRE "PACIENTE SIN ANALISIS CLINICO" FROM PACIENTE WHERE ID_PACIENTE NOT IN(SELECT ID_PACIENTE FROM ANALISIS_CLINICO);
-- 17: Consultar el nombre completo de los pacientes que sacaron cita pero no asistieron a la consulta.
SELECT * FROM PACIENTE;
SELECT * FROM CITA;
SELECT * FROM CONSULTA;
SELECT APATERNO, AMATERNO, NOMBRE FROM PACIENTE P JOIN CITA C ON P.ID_PACIENTE = C.ID_PACIENTE WHERE P.ID_PACIENTE NOT IN(SELECT ID_PACIENTE FROM CONSULTA);
-- 18: Consultar el nombre completo de los pacientes que fueron consultados pero que no fueron hospitalizados.
SELECT * FROM CONSULTA;
SELECT * FROM HOSPITALIZACION;
SELECT * FROM PACIENTE;
SELECT APATERNO, AMATERNO, NOMBRE FROM PACIENTE P JOIN CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE WHERE P.ID_PACIENTE NOT IN(SELECT ID_PACIENTE FROM HOSPITALIZACION);
-- 19: Consultar el nombre completo de la asistente del mes (La asistente que m�s cita gener� en un determinado mes).
SELECT * FROM ASISTENTE;
SELECT * FROM CITA;
SELECT A.APATERNO, A.AMATERNO, A.NOMBRE, COUNT(*) AS CITAS_EN_MAYO FROM ASISTENTE A JOIN CITA C ON A.ID_ASISTENTE = C.ID_ASISTENTE
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) FROM ASISTENTE A JOIN CITA C ON A.ID_ASISTENTE = C.ID_ASISTENTE WHERE FECHA BETWEEN '01-05-20' AND '30-05-20'
GROUP BY APATERNO , AMATERNO, NOMBRE);
-- 20: Consultar el nombre completo del m�dico que menos consultas ha tenido.
SELECT * FROM MEDICO;
SELECT * FROM CONSULTA;
SELECT M.APATERNO, M.AMATERNO, M.NOMBRE, COUNT(*) AS CONSULTAS FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
GROUP BY APATERNO, AMATERNO, NOMBRE
HAVING COUNT(*) = (
SELECT MIN(COUNT(*)) FROM MEDICO M JOIN CONSULTA C ON M.ID_MEDICO = C.ID_MEDICO
                                                  JOIN PACIENTE P ON P.ID_PACIENTE = C.ID_PACIENTE
GROUP BY M.APATERNO, M.AMATERNO, M.NOMBRE);